### ISSUE TITLE
Duplication of hmac?

### ISSUE THREAD

**Issue by AdamISZ** [BitcoinAuthenticator/Subspace#13]
I might be wrong, but looking at: https://github.com/cpacia/Subspace/blob/master/subspace/message.py#L61

It seems you apply an HMAC to the payload, but were you aware that alice.encrypt() in pyelliptic is already applying an HMAC? (it returns ciphertext+mac, i.e. it's an encrypt-then-mac).

Unless I missed something, you get the signature-with-repudiability already "out of the box"; they throw mac errors in decrypt()

**Comment by cpacia** [comment]
Yeah I am aware, but pyelliptic just uses an ephemeral key pair for encryption and the hmac not the sender's long lived public key. If all we used was the outer hmac we would get message integrity but we couldn't prove who sent the message. 

If we used our long lived public key in the outer encryption and hmac we would blow our privacy as the public key is attached to the ciphertext. 

We could modify pyelliptic to get rid of the hmac, but I don't see any harm in keeping it.

**Comment by AdamISZ** [comment]
Yes, I see. The ECIES encrypt is replicating the "encrypt a message" function, but not signature, hence it uses an ephemeral pubkey for the sender. Meanwhile you don't want to use the inbuilt pyelliptic sign() because that's a traditional digital sig (ECDSA) with non-repudiability, hence you go with HMAC for "signing" (authenticating) the sender's identity.

Looked at that way, it kind of makes sense that there are two authentications, the outer one is authentication of the ephemeral message channel between two parties, while the inner one is a "signature" (repudiable) by the sender. (maybe.. I need to read more).

(BTW this is not really appropriate as a github "Issue", I'll contact you via other channels if I have other similar "is that right?" or "what does that do" questions).

**Comment by cpacia** [comment]
> Looked at that way, it kind of makes sense that there are two authentications, the outer one is authentication of the ephemeral message channel between two parties, while the inner one is a "signature" (repudiable) by the sender. (maybe.. I need to read more).

You got it.

> (BTW this is not really appropriate as a github "Issue", I'll contact you via other channels if I have other similar "is that right?" or "what does that do" questions).

Sure my email is ctpacia@gmail.com
