### ISSUE TITLE
Openname verification

### ISSUE THREAD

**Issue by cpacia** [BitcoinAuthenticator/Subspace#5]
At present there no way to verify that a sender who uses an openname is the owner of that name. 

What we need to do is put the subspace address in the openname profile. The recipient's client can then check the address in the profile matches the address of the sender.

I'm trying to get Ryan and Muneeb to modify the profile format to support a messenger address.

**Comment by taoeffect** [comment]
@cpacia Have a look at profiles v3 spec: https://github.com/openname/openname-specifications/blob/master/profiles/profiles-v03.md

You may be able to use one or more of `"pubkeys"`, `"profiles"`, or `"statements"` to do this. If not, could you be clearer about what you're looking for?

**Comment by taoeffect** [comment]
Also have a look at our [BlockchainID](https://github.com/okTurtles/blockchainid) spec (an augmentation to the openname profile spec) that might be useful for you.

Let me know if you have any questions!

**Comment by cpacia** [comment]
Thanks. Any one of those fields would likely work. I just need to be able to enter it via their website. It's too much to ask of users to manually build a profile. Last I checked it didn't give an option to put in those other fields.
