### ISSUE TITLE
Is this a polling protocol?

### ISSUE THREAD

**Issue by inaltoasinistra** [BitcoinAuthenticator/Subspace#9]
Hello,
sorry, I don't know where ask so I opend this issue.

> Server B queries the DHT to find the IP address of the server(s) storing the message.

B (or it's server) should polling the DHT to be aware of new messages?

Thanks!
Martino

**Comment by cpacia** [comment]
Hey Martino

I'm currently reconfiguring the protocol design a bit so the readme isn't that accurate. I'll update it when I'm a little bit further along.

But as it stands now to receive a message you enter the dht with your public key and your neighbors will send you all the stored messages they have... some of which will be for you.

If you keep the software open, those sending a message will place a store request in your neighborhood meaning you will receive new messages as they come in.

By enabling a 'server' flag a node can act as a webserver for light weight clients which, yes, would poll the server for new messages, but that's only for clients that don't want to implement the full protocol.
